SELECT c.[CustomerKey]
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,c.[FirstName] as[First Name]
      --,[MiddleName]
      ,c.[LastName] as [Last Name]
	  , CONCAT(FirstName,' ',LastName) as [Full Name]
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      ,case c.[Gender] when 'M' then 'Male' else 'Female' end as Gender
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
     -- ,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
     -- ,[HouseOwnerFlag]
     -- ,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,c.[DateFirstPurchase]
      --,[CommuteDistance]
	  ,g.City as [Customer City]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer] as c
  join AdventureWorksDW2019.dbo.DimGeography as g
  on c.GeographyKey = g.GeographyKey
  order by c.CustomerKey asc